# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milstd2525/ui/sidcdialogbase.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SidcDialog(object):
    def setupUi(self, SidcDialog):
        SidcDialog.setObjectName("SidcDialog")
        SidcDialog.resize(617, 497)
        self.verticalLayout = QtWidgets.QVBoxLayout(SidcDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboStandardId1 = QtWidgets.QComboBox(SidcDialog)
        self.comboStandardId1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboStandardId1.setObjectName("comboStandardId1")
        self.gridLayout.addWidget(self.comboStandardId1, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(SidcDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(SidcDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(SidcDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(SidcDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(SidcDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(SidcDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SidcDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(SidcDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboModifier1 = QtWidgets.QComboBox(SidcDialog)
        self.comboModifier1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboModifier1.setObjectName("comboModifier1")
        self.gridLayout.addWidget(self.comboModifier1, 8, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(SidcDialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.comboModifier2 = QtWidgets.QComboBox(SidcDialog)
        self.comboModifier2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboModifier2.setObjectName("comboModifier2")
        self.gridLayout.addWidget(self.comboModifier2, 9, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(SidcDialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.comboStandardId2 = QtWidgets.QComboBox(SidcDialog)
        self.comboStandardId2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboStandardId2.setObjectName("comboStandardId2")
        self.gridLayout.addWidget(self.comboStandardId2, 1, 1, 1, 1)
        self.comboSymbolSet = QtWidgets.QComboBox(SidcDialog)
        self.comboSymbolSet.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboSymbolSet.setObjectName("comboSymbolSet")
        self.gridLayout.addWidget(self.comboSymbolSet, 2, 1, 1, 1)
        self.comboStatus = QtWidgets.QComboBox(SidcDialog)
        self.comboStatus.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboStatus.setObjectName("comboStatus")
        self.gridLayout.addWidget(self.comboStatus, 3, 1, 1, 1)
        self.comboHQ = QtWidgets.QComboBox(SidcDialog)
        self.comboHQ.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboHQ.setObjectName("comboHQ")
        self.gridLayout.addWidget(self.comboHQ, 4, 1, 1, 1)
        self.comboEchelon = QtWidgets.QComboBox(SidcDialog)
        self.comboEchelon.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboEchelon.setObjectName("comboEchelon")
        self.gridLayout.addWidget(self.comboEchelon, 5, 1, 1, 1)
        self.comboIcon = QtWidgets.QComboBox(SidcDialog)
        self.comboIcon.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboIcon.setObjectName("comboIcon")
        self.gridLayout.addWidget(self.comboIcon, 6, 1, 1, 1)
        self.comboSubtypes = QtWidgets.QComboBox(SidcDialog)
        self.comboSubtypes.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboSubtypes.setObjectName("comboSubtypes")
        self.gridLayout.addWidget(self.comboSubtypes, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(SidcDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SidcDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtCode = QtWidgets.QLineEdit(SidcDialog)
        self.txtCode.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCode.setFont(font)
        self.txtCode.setFrame(False)
        self.txtCode.setObjectName("txtCode")
        self.horizontalLayout.addWidget(self.txtCode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(311, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelImg = QtWidgets.QLabel(SidcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImg.sizePolicy().hasHeightForWidth())
        self.labelImg.setSizePolicy(sizePolicy)
        self.labelImg.setMinimumSize(QtCore.QSize(100, 100))
        self.labelImg.setMaximumSize(QtCore.QSize(100, 100))
        self.labelImg.setBaseSize(QtCore.QSize(100, 100))
        self.labelImg.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.horizontalLayout_2.addWidget(self.labelImg)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(311, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(SidcDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SidcDialog)
        self.buttonBox.accepted.connect(SidcDialog.accept)
        self.buttonBox.rejected.connect(SidcDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SidcDialog)

    def retranslateUi(self, SidcDialog):
        _translate = QtCore.QCoreApplication.translate
        SidcDialog.setWindowTitle(_translate("SidcDialog", "SIDC code"))
        self.label_8.setText(_translate("SidcDialog", "Icon"))
        self.label_9.setText(_translate("SidcDialog", "Special entity subtypes"))
        self.label_2.setText(_translate("SidcDialog", "StandardIdentity2"))
        self.label_6.setText(_translate("SidcDialog", "Headquarters/task force/dummy"))
        self.label_5.setText(_translate("SidcDialog", "Status"))
        self.label_7.setText(_translate("SidcDialog", "Echelon/mobility/towed array"))
        self.label_3.setText(_translate("SidcDialog", "StandardIdentity1"))
        self.label_4.setText(_translate("SidcDialog", "Symbol set"))
        self.label_10.setText(_translate("SidcDialog", "Icon modifier 1"))
        self.label_11.setText(_translate("SidcDialog", "Icon modifier 2"))
        self.label.setText(_translate("SidcDialog", "SIDC code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SidcDialog = QtWidgets.QDialog()
    ui = Ui_SidcDialog()
    ui.setupUi(SidcDialog)
    SidcDialog.show()
    sys.exit(app.exec_())

